{% set version = "0.1.3a1" %}

package:
  name: ipywe
  version: {{ version }}

source:
  url: https://github.com/scikit-beam/ipywe/archive/{{ version }}.tar.gz
  sha256: 507300c458c1db3bf42e8168530105d4a96d0bbdaa910ebf9d5bf3b4df65c414

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [win]

requirements:
  build:
    - python
    - pip
    - nodejs
  run:
    - python
    - ipywidgets >=6.0.0
    - traitlets >=4.3.0
    - pillow
    - numpy
    - scipy

test:
  imports:
    - ipywe

about:
  home: https://github.com/scikit-beam/ipywe
  license: MIT
  license_family: MIT
  # license_file: LICENSE
  summary: 'jupyter widgets extension for scattering sciences'
  doc_url: https://github.com/scikit-beam/ipywe
  dev_url: https://github.com/scikit-beam/ipywe

extra:
  recipe-maintainers:
    - yxqd
