{% set version = "0.1.3a2" %}

package:
  name: ipywe
  version: {{ version }}

source:
  url: https://github.com/scikit-beam/ipywe/archive/{{ version }}.tar.gz
  sha256: 76985677fded5b9e2309a1a3d132254f079de042a0bebb6b80bc0900d7984f3a
build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [win]

requirements:
  build:
    - nodejs >=12
  host:
    - python
    - pip
  run:
    - python
    - jupyter
    - ipywidgets >=6.0.0
    - traitlets >=4.3.0
    - pillow
    - numpy
    - scipy

test:
  imports:
    - ipywe

about:
  home: https://github.com/scikit-beam/ipywe
  license: MIT
  license_file: LICENSE
  license_family: MIT
  # license_file: LICENSE
  summary: 'jupyter widgets extension for scattering sciences'
  doc_url: https://github.com/scikit-beam/ipywe
  dev_url: https://github.com/scikit-beam/ipywe

extra:
  recipe-maintainers:
    - yxqd
