travis:
  secure:
    BINSTAR_TOKEN: j8q/t8LbDNyLlkgXwjc4GsmCMloJ3N+BknVnfe3mY4TE4Oq5U7A3CiprunmQb/N8F672Toebr4TDcyJn/WVeO4in1Qw/U0MM7aKz9eFzYlRCCYmo/8ACLoVnZqkEXo3XH9kCDhnV3as/1e77DVHAIwAFVPRSf2D55VwkuVrWy1YIKTh5PuUV8fPqckhP0YY39tpuZxrx4uraibiHcg6oXa23oir8E7HPkQvoegRehk7D49NXIx4iyKwbQUpxC3GvQgYummCZMz3xldsDowV75CjtAppKfBtl8rxG3ZW0I3TNa1yUrVHene0eQgiB5YfU3MwHfml2gDkQ9T+nLI8pcxsptcJu6yYInBvRJTRKhFxgen4bKrXpl12diemrPTwErQaSlx1knsEAxbBHcZwMwITt+Ccttgq6Ry+cSL+Q4IEqCk8SrdOxlixjGg44XeyKDgzbPZx2rmqWjSlde01J/ajYuJly55/FmMVupfIJbf+FRfWVRMF3bjGc6RvHYqKlP/CKr6FbETx1hHShfAGSdN+4rLgkkEHI/gDV58unaeqeTXy8owbO0+q1Eozz+YIaSa8ygj3gcRnHtpyfTc7gNx34+HqavihPBl1QxkR/UB3bXXGMsy2BPokW8k7UAJpodigu2XV0QqNwfCSiKiVo52C4SonNGoBko/vF/Exu+dQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
