travis:
  secure:
    BINSTAR_TOKEN: bTY7ixBTepal1PidT5PDIkJikXL4tfnYzwGIbtvGktvFFJYbI6Gwia62coDnCrgQ/VGaFzVTKIVhS/nYUxua28nvngSi0UONqm+kDDF2oe0vlQbeIPtuTaga3L04Ww2TFq7eogQ8ZPONeBzGbTxyfu7asLdO37EIV+5qnL1h51MCaYmDBijgSYe6CXIoPD3FoMVjf5fdysaaZmYGDEN2uMaAwMSe5JuPMBbch7fdBuOGe+2JbDlR7IQuXeqDl/5992TPdICSdsBnKzdb0rE26SCQJaoq+ALp9eQRD8ZlyTrGJQxNcdvpqViDi8I6ekurXsqwr+cbCIsxfS9sLOyVoYKm1Vk3PgFiyd5uGDP3h/McH9n7hTx7nlKfUAMjvRKDWss8byKOj5hup8G0jD3QO6sAvNuYuedzvBJB+3x49LL1kDs4xJ+/36QVehwcnJWAms+l908Sz3XfGNRawuZP7W/k7R+1h+cUFkhfI7OuIPIO0BFHgBymt50ckmiTVWuxQahxgp5biO6VzyjqOkDK8osMkRojsJ5gST/nvPTuDjouBDWhsfh03n9sC5EapkDO3L/TtTcGAMWABNq8UiCTQBwUVaa+Xm3eAeASj8R8PrhLH8kquvfpfhrrKucF7JmC59cyh4miUBiT4MFI+1abhbnd3m4Qys5VIsoMcR5Q0tk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
